apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-k8s-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-k8s-deployment
  template:
    metadata:
      labels:
        app: react-k8s-deployment
    spec:
      containers:
        - name: react-k8s-deployment
          image: react-k8s:1
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: react-k8s-service
spec:
  selector:
    app: react-k8s-deployment
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 3000

